#基础路径的配置：
base_url: https://api.weixin.qq.com
#base_url: https://api.weixin.qq.com
#日志的配置
log:
  log_file_name: logs_
  log_level:
  log_format:  '[%(asctime)s] %(filename)s->%(funcName)s line:%(lineno)d [%(levelname)s]%(message)s'

# 数据库配置：
database_config:
  host: shop-xo.hctestedu.com
  port: 3306
  database: shopxo_hctested
  user: api_test
  password: Aa9999!

